--liquibase formatted sql

--changeset table_order_products:1
create table order_products
(
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null

);
--rollback DROP TABLE order_products;

--changeset table_product:2
create table products
(
    id bigint generated by default as identity,
    name varchar(25) not null,
    picture_url varchar(55),
    price double precision
);
--rollback DROP TABLE products;

--changeset users:3
CREATE USER read_user;
CREATE USER write_user;
CREATE USER admin_user;
--rollback DROP USER read_user write_user admin_user;

--changeset table_product:4
alter table products alter column name type varchar(255) using name::varchar(255);
alter table products alter column picture_url type varchar(255) using picture_url::varchar(255);
--rollback
alter table products alter column name type varchar(25) using name::varchar(25);
alter table products alter column picture_url type varchar(55) using picture_url::varchar(55);

--changeset user_access:5
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO write_user;
GRANT INSERT ON ALL TABLES IN SCHEMA public TO write_user;
GRANT ALL privileges ON DATABASE postgres TO admin_user;
