create table order_products
(
    quantity integer not null,
    order_id bigint not null,
    product_id bigint not null

);

create table orders
(
    id bigint generated by default as identity,
    date_created date,
    status varchar(255)
);

create table products
(
    id bigint generated by default as identity,
    name varchar(25) not null,
    picture_url varchar(55),
    price double precision
);
